### ISSUE TITLE
[FEATURE REQUEST] different flags for navy and pirate side

### ISSUE THREAD

**Issue by LOtter15** [cheesenibbles123/Alternion-BW-mod#27]
being able to assign different flags for navy and pirate side

**Comment by cheesenibbles123** [comment]
Will require json changes and break backwards compatibility, So I'll leave this till v8 rather than including it in v7.1

**Comment by cheesenibbles123** [comment]
Is implemented in the latest beta version. Will be pushed to v8 soon:tm:
